<?php
# Authorize.net Payment Gateway Credentials
$AUTHORIZE_NET_API_LOGIN_ID         ="AUTHORIZE_NET_API_LOGIN_ID";
$AUTHORIZE_NET_TRANSACTION_KEY      ="AUTHORIZE_NET_TRANSACTION_KEY";
$AUTHORIZE_NET_SECRET_KEY           ="AUTHORIZE_NET_SECRET_KEY";
$AUTHORIZE_NET_SANDBOX_GATEWAY_ID   ="AUTHORIZE_NET_SANDBOX_GATEWAY_ID";
#
# Application environment variables
$APP_ENV="local";
#
